### ISSUE TITLE
How to run on a cluster without workload manager

### ISSUE THREAD

**Issue by slambrechts** [franciscozorrilla/unseenbio_metaGEM#1]
Dear Francisco,

I realize metaGEM was optimized to run on a HPC cluster system, but the cluster of our lab (40 cores, 500 GB RAM) operates without a workload manager. So as a user you have to take care you don't use all 40 cores, and that you do not submit more jobs then there are cores etc. 

I have 43 (soil) samples organized into sample specific subdirectories within the dataset folder

If I run

`bash metaGEM.sh --task megahit --local`

and I set megahit cores to 24 in the config.yaml file,

Would that mean metaGEM would assemble the samples only one at a time? What I want to avoid is that the metagem parser submits all 43 jobs at once, because on this cluster submitting means starting

Best wishes,
Sam

**Comment by slambrechts** [comment]
Closing this because I meant to post this in the general metaGEM repo

**Comment by franciscozorrilla** [comment]
Link to issue [here](https://github.com/franciscozorrilla/metaGEM/issues/44)
