### ISSUE TITLE
MissingInputException in line 145 of /home/yw/desktop/metaGEM/Snakefile:

### ISSUE THREAD

**Issue by tan-yuwei** [franciscozorrilla/unseenbio_metaGEM#2]
Dear Francisco,

Hi!

In order to solve errors cauesd by snakemake version, I donwloaded a file "snakemake-5.10.0.tar.gz". Then I replaced the original snakemake file in "metaGEM/envs/metaGEM/snakemake" by new snakemake file in "snakemake-5.10.0.tar.gz". When I tried to run a commond {bash metaGEM.sh -t fastp -j 2 -c- 2 -m 20 -h 2}, it showed errors as followed:
Unlocking snakemake ...
Building DAG of jobs ...
MissingInputException in line 145 of /home/yw/desktop/metaGEM/Snakefile:
Missing input files for rule qfilter:
/home/yw/desktop/metaGEM/dataset/testdata1/testdata_R2.fastq.gz
/home/yw/desktop/metaGEM/dataset/testdata1/testdata_R1.fastq.gz

Looking forward your reply,

Kind regards,
yw

**Comment by franciscozorrilla** [comment]
Hi Yuwei,

Thanks for opening an issue, in the future please open issues in the main [metaGEM repo](https://github.com/franciscozorrilla/metaGEM).

Could you please check that the short read files are present and properly named in the input folder? e.g.

```
ls -la /home/yw/desktop/metaGEM/dataset/testdata1/ 
```

Please make sure that the files are present in this folder, and also that they are named as expected by the metaGEM output, i.e. testdata_R1.fastq.gz & testdata_R2.fastq.gz. For more on this please refer to the [quickstart page](https://github.com/franciscozorrilla/metaGEM/wiki/Quickstart#input-data) in the wiki.

Best wishes,
Francisco
